## Home
GET http://localhost:3000
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE1OTc1OTY3MzAsImV4cCI6MTU5NzU5Njc2MCwiYXVkIjoiNWYzNmViODcyMTU3ZjUxYjEwZmM4NmZkIiwiaXNzIjoibmVjdGlhLmNvbSJ9.95_LmfadPWJIhQIyA7xxJWb610H0O2Wp1ogniOdxqxs

### Login
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email" : "test@nectia.com",
    "password" : "1234"
}

### Register
POST http://localhost:3000/auth/register
Content-Type: application/json

{
    "email" : "test@nectia.com",
    "password" : "1234"
}

### Refresh Token
POST http://localhost:3000/auth/refresh-token
Content-Type: application/json

{
    "refreshToken" : "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE1OTc1OTY3NjYsImV4cCI6MTYyOTE1NDM2NiwiYXVkIjoiNWYzNmViODcyMTU3ZjUxYjEwZmM4NmZkIiwiaXNzIjoibmVjdGlhLmNvbSJ9.g1T_k-VEse9awhzaDOV7DkboDpOoqJOPY4kaDR8sHco"
}

### Logout
DELETE http://localhost:3000/auth/logout
Content-Type: application/json

{
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE1OTc1OTU3NTMsImV4cCI6MTYyOTE1MzM1MywiYXVkIjoiNWYzNmViODcyMTU3ZjUxYjEwZmM4NmZkIiwiaXNzIjoibmVjdGlhLmNvbSJ9.yoGwDFZ7FZ38EmVhSIVAp_9IQw7mPhp2ddAeE10c_KY"
}

### Error
GET http://localhost:3000/abc